joint_limits:
  shoulder_pan_joint:
    has_position_limits: true
    max_position: 6.283
    min_position: -6.283
    max_effort: 150.0
    has_acceleration_limits: true
    max_acceleration: 1.225
  shoulder_lift_joint:
    has_position_limits: true
    max_position: -0.6
    min_position: -2.5
    max_effort: 150.0
    has_acceleration_limits: true
    max_acceleration: 1.225
  elbow_joint:
    has_position_limits: true
    max_position: 6.28
    min_position: -6.28
    max_effort: 150.0
    has_acceleration_limits: true
    max_acceleration: 1.225
  wrist_1_joint:
    has_position_limits: true
    max_position: 6.283
    min_position: -6.283
    max_effort: 150.0
    has_acceleration_limits: true
    max_acceleration: 1.225
  wrist_2_joint:
    has_position_limits: true
    max_position: 6.283
    min_position: -6.283
    max_effort: 28.0
    has_acceleration_limits: true
    max_acceleration: 1.225
  wrist_3_joint:
    has_position_limits: true
    max_position: 6.283
    min_position: -6.283
    max_effort: 28.0
    has_acceleration_limits: true
    max_acceleration: 1.225
  robotiq_85_left_knuckle_joint:
    has_acceleration_limits: true
    max_acceleration: 1.225
  robotiq_85_right_knuckle_joint:
    has_acceleration_limits: true
    max_acceleration: 1.225    